site_name: ChaosIQ Documentation
site_author: ChaosIQ Limited
site_description: ChaosIQ Documentation
copyright: '&copy; 2020 ChaosIQ Limited'
theme:
  name: material
  favicon: "static/images/favicon.ico"
  logo: "static/images/chaosiq-mark.png"
  font:
    text: "IBM Plex Sans"
    code: "IBM Plex Mono"
extra_css:
  - css/styles.css
nav:
- Welcome: index.md
- The Reliability Workflow: reliability-workflow/reliability-workflow.md
- Getting Started:
    - Introduction: gettingstarted/introduction.md
    - Install Chaos Toolkit: gettingstarted/install-ctk.md
    - Add the ChaosIQ Plugin to your Chaos Toolkit: gettingstarted/add-chaos-iq.md
    - Create your first Objective: gettingstarted/first-objective.md
    - Create your first Verification: gettingstarted/first-verification.md
    - Run your first Verification: gettingstarted/run-first-verification.md
- Organizations and Teams:
    - Introduction: organizations-and-teams/organizations-and-teams-intro.md
    - Creating an Organization: organizations-and-teams/create-organization.md
    - Inviting people to your Organization: organizations-and-teams/invite-to-an-organization.md
    - Creating a Team: organizations-and-teams/creating-a-team.md
    - Publishing Verifications to a Team: organizations-and-teams/publishing-to-a-team.md
    - Switching Teams: organizations-and-teams/switching-teams.md
    - Switching Organizations: organizations-and-teams/switching-organizations.md
- Deployment Options: deployment-options/deployment-options.md 
